services:
  inference:
    container_name: inference-eth
    env_file:
      - .env
    build: .
    command: python -u /app/app.py
    ports:
      - "8003:8003"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://inference:8003/inference/${TOKEN}"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - ./inference-data:/app/data
  
  updater:
    container_name: updater-eth
    build: .
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8003
    command: >
      sh -c "
      while true; do
        python -u /app/update_app.py;
        sleep 24h;
      done
      "
    depends_on:
      inference:
        condition: service_healthy


volumes:
  inference-data:
